image: node:latest

stages:
  - lint
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm ci --force

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test